### ISSUE TITLE
Successfully registering as a doctor, even with an existing patient's e-mail

### ISSUE THREAD

**Issue by TilapiaRoger** [BiancaBenedictos/STSWENG-MedApp#11]
**Original Report Date:** January 18, 2021
**By:** Jamie & Curry co.
**Platform:** Google Chrome
**Branch:** developing-temp branch

**Type:** (**Coding Error**/Design Issue/Suggestion)
**Severity:** (Fatal/**Serious**/Minor)

**Description:**
Registering as doctor with an existing address of patient leads to successful registration.

**Steps to Reproduction:**
1. Register as a patient
2. Fill in all forms.
3. Register.
4. Log out.
5. Register as a Doctor.
6. Fill in all forms, including an existing e-mail address.
7. Register.

**Expected Results:**
If registering as a doctor with an already existing patient address, the user should still be in the register page with an error notice "Email address is already in use".

**Actual Results:**
Registering with an existing patient address will lead to the account being created without warning. As a result, logging in again with the same e-mail address will cause the patient to be logged in, instead of the doctor's account with same e-mail address, which is now inaccessible.

**Screenshots:**
Registering as a patient
![screenshot](https://user-images.githubusercontent.com/47263309/104858192-8f3bff00-5958-11eb-9127-a20ebaece3e4.png)

Successful patient registration
![screenshot 2](https://user-images.githubusercontent.com/47263309/104858196-94994980-5958-11eb-9f76-b6de1baa258d.png)

Registering as a doctor with existing patient e-mail address
![screenshot 3](https://user-images.githubusercontent.com/47263309/104858203-a11da200-5958-11eb-8722-c2a48523ab5a.png)

Successful doctor registration, despite using the already existing patient e-mail address
![screenshot 4](https://user-images.githubusercontent.com/47263309/104858207-a4b12900-5958-11eb-83f1-5147a9dfabbb.png)

Logging in with the test e-mail address
![screenshot 5](https://user-images.githubusercontent.com/47263309/104858225-b266ae80-5958-11eb-8878-9868ac690077.png)

Logging in with the e-mail address leads to patient's account with the e-mail address and no accessibility to the doctor with the same e-mail address.
![screenshot 6](https://user-images.githubusercontent.com/47263309/104858240-b692cc00-5958-11eb-9904-338dcdf091c7.png)

Command Prompt output of registered patient
![cmd screenshot](https://user-images.githubusercontent.com/47263309/104858163-5e5bca00-5958-11eb-90b9-38f4a31f7001.png)

Command Prompt output of registered doctor
![cmd screenshot 2](https://user-images.githubusercontent.com/47263309/104858183-851a0080-5958-11eb-90ac-ecd3ae226148.png)

**Suggested Fix:**
For the MongoDB function for the doctor registration, add an operation to check if a patient with the same e-mail already exists.

**Comment by mikatej** [comment]
**Report Date**: January 26, 2021
**By**: Mika Tejada
**Platform**: Google Chrome
**Branch**: developing branch

**Type**: (**Coding Error**/Design Issue/Suggestion)
Severity: (Fatal/**Serious**/Minor)

**Description**:
Registering as doctor with an existing address of patient leads to successful registration.

**Steps to Reproduction**
1. Go to http://localhost:3000/doctorRegister
2. Register as a doctor with the email: test@gmail.com (email of an existing patient account)
3. Input "test1" as the password (different password from the existing patient account)
4. Fill in the remaining fields.
5. Click Register.
6. Log out.
7. Check the list of doctors in the db.

**Expected Results**:
If registering as a doctor with an already existing patient address, the user should still be in the doctor's register page with an error notice "Email address is already in use".

**Actual Results**:
Registering with an existing patient address will lead to the account being created without warning. Logging in again with the same e-mail address but different password will show an error message: The username or password is not valid.

**Screenshots**:
Existing patient email from the db
![image](https://user-images.githubusercontent.com/57044177/105800780-85f30800-5fd2-11eb-8787-c4b2ca3d8353.png)

Register as a doctor using test@gmail.com as the email.
![image](https://user-images.githubusercontent.com/57044177/105801148-77f1b700-5fd3-11eb-9b1c-597df869e12e.png)

Successful registration of doctor.
![image](https://user-images.githubusercontent.com/57044177/105846928-dccf0080-6017-11eb-8ebe-84c2737f51c9.png)
![image](https://user-images.githubusercontent.com/57044177/105846972-f1ab9400-6017-11eb-9b3b-eb6a210d8fb3.png)

Newly created doctor's account was added to the db.
![image](https://user-images.githubusercontent.com/57044177/105848570-1bfe5100-601a-11eb-8939-d66fe838ea17.png)

After logging out and trying to log in again using the created doctor's account.
![image](https://user-images.githubusercontent.com/57044177/105847224-47803c00-6018-11eb-82e5-251c47019509.png)
