### ISSUE TITLE
[US 5] Verify Doctors

### ISSUE THREAD

**Issue by mikatej** [BiancaBenedictos/STSWENG-MedApp#37]
**Report Date**: January 29, 2021
**By**: Mika Tejada
**Platform**: Google Chrome
**Branch**: developing branch

**Type**: (**Coding Error**/Design Issue/Suggestion)
**Severity**: (Fatal/**Serious**/Minor)

Description:
The site will crash when any option in the dropdown of the navbar is clicked. (us5 works before)

Steps to Reproduction:
1. Go to http://localhost:3000/
2. Login as a admin.
3. Click any option from the dropdown of the navbar.

Expected Results:
The admin will be redirected to the page of the selected option.

Actual Results:
The site crashes.

Screenshots:
Admin navbar:
![image](https://user-images.githubusercontent.com/57044177/106290004-ead58900-6284-11eb-850a-ecc625820f24.png)

After clicking verify doctors:
![image](https://user-images.githubusercontent.com/57044177/106291492-a8ad4700-6286-11eb-9d76-2f1fa9fa2cf5.png)

**Comment by drbuhion** [comment]
Note that US 6-7 is also affected by the same problem
