### ISSUE TITLE
App Crashes upon Registration with Missing Credentials

### ISSUE THREAD

**Issue by niiickm** [BiancaBenedictos/STSWENG-MedApp#5]
**Description:**
The webapp crashes upon registering a new Doctor account without submitting a Credentials file. There is no indicator that it is required when not filled out like in the other required fields. The app seemingly allows the registration to go through.

**Steps to reproduce:**
1.  Open the web-app
2. From the landing page, go to the Doctor Registration Form through clicking "create an account as a Doctor"
3. Fill in the First Name, Last Name, Email, Password, and Confirm Password fields
4. Press the register button

**Expected results:**
Either the registration goes through and redirects me to a new page, or an error message indicating that the Credentials field is empty.

**Actual results:**
Site crashes.

**Suggestions:**
There should be a warning/error message indicating that it is a required field if it is empty upon pressing the "register" button. The app shouldn't also proceed with its processes if it detects that the "Credentials" field is empty.

**Screenshots:**
Register button was pressed without touching any of the fields to show the error messages.
![image](https://user-images.githubusercontent.com/57778935/104563487-ae027300-5684-11eb-8a56-3c24caf5df77.png)
Upon pressing register:
![image](https://user-images.githubusercontent.com/57778935/104563636-dab68a80-5684-11eb-8782-4c2124399490.png)
The CLI running the app:
![image](https://user-images.githubusercontent.com/57778935/104563687-ec982d80-5684-11eb-8f1b-9343e67860d9.png)

**Comment by mikatej** [comment]
**Report Date**: January 26, 2021
**By**: Mika Tejada
**Platform**: Google Chrome
**Branch**: developing branch

**Type**: (**Coding Error**/Design Issue/Suggestion)
Severity: (Fatal/**Serious**/Minor)

**Description**:
The application crashes when registering a new doctor account without uploading a Credentials file. 

**Steps to Reproduction**:
1. Go to http://localhost:3000/doctorRegister
2. Properly fill in the all fields but do not upload a file for the credentials
3. Click register

**Expected Results**:
An error message stating that uploading credentials is required in order for the registration to be successful must appear under the credentials field.

**Actual Results**:
The application crashes and the registration was not reflected in the db.

**Screenshots**:
Signing up as a doctor without uploading credentials.
![image](https://user-images.githubusercontent.com/57044177/105850448-b3fd3a00-601c-11eb-9341-c37069c736c7.png)

After clicking register:
![image](https://user-images.githubusercontent.com/57044177/105850517-ca0afa80-601c-11eb-82cf-dc3145d5faa4.png)

Result in CLI:
![image](https://user-images.githubusercontent.com/57044177/105850697-06d6f180-601d-11eb-9218-a25b11d67ae8.png)
