### ISSUE TITLE
Redirect after Editing Profile

### ISSUE THREAD

**Issue by niiickm** [BiancaBenedictos/STSWENG-MedApp#6]
**Description:**
Upon logging in as a doctor, going to the "Edit profile page", and pressing "save", I was presented with a different edit page.

**Steps to reproduce:**
1. Open the webapp.
2. Log-in with a doctor account.
3. Toggle the drop down menu through the name, and go to Edit Profile.
4. Press "save".

**Suggestions:**
One option is redirect to another page (e.g. a dedicated profile page or the homepage) after pressing save, though staying on the same page is also alright. There should also be a message upon pressing "save" to indicate that the changes have been reflected.

**Screenshots:**
Edit profile page
![image](https://user-images.githubusercontent.com/57778935/104567230-8530ac80-5689-11eb-9924-dce77bb280e6.png)
After pressing save
![image](https://user-images.githubusercontent.com/57778935/104567253-8e217e00-5689-11eb-967f-7313fd4c5a9d.png)

**Comment by reqinamarie** [comment]
Feature not yet implemented in this branch.
