### ISSUE TITLE
User cannot enter decimal values in the weight field of account registration

### ISSUE THREAD

**Issue by diannech** [BiancaBenedictos/STSWENG-MedApp#9]
![report3](https://user-images.githubusercontent.com/60427762/104807208-2baab800-5818-11eb-8f87-2d7ec0c8a11b.jpg)

**Comment by mikatej** [comment]
**Report Date**: January 26, 2021
**By**: Mika Tejada
**Platform**: Google Chrome
**Branch**: developing branch

**Type**: (Coding Error/**Design Issue**/Suggestion)
Severity: (Fatal/Serious/**Minor**)

**Description**:
Entering decimal values in the weight field when registering a new patient account is considered invalid.

**Steps to Reproduction**:
1. Go to http://localhost:3000/patientRegister
2. Register as a patient and input "55.7" in the weight field
3. Properly fill in the remaining fields
4. Click register

**Expected Results**:
Signing up as a patient and filling in the weight field with decimal values must be valid. After clicking the register button, the user must be able to successful register as a patient and be redirected to the home page of the application.

**Actual Results**:
A prompt appears with the message: Please enter a valid value. The two nearest values are 55 and 56.

**Screenshots**:
![image](https://user-images.githubusercontent.com/57044177/105850130-47823b00-601c-11eb-8507-d83aa6761faa.png)
